### ISSUE TITLE
Entregable: repositorios y mockups

### ISSUE THREAD

**Issue by yodra** [fullstacktf/PetDev-FrontEnd#1]
Faltan los mockups que realizamos durante clase, para irlos evolucionando y con ellos sacar tareas/funcionalidades que implementaremos a futuro.

Hay que añadir la rama de *develop*

No era necesario subir las configuraciones de babel, linter, etc ya que aun queda opciones que ver en clase para elegir cómo configurar el proyecto.

**Comment by milanes** [comment]
**Realizado**
Acabo de ver que no te habiamos contestado. ¡Ya tenemos realizado esa parte!.
